# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ExampleApp' do

pod 'NFIFramework', :path => ‘../‘
pod 'Realm'
pod 'SDWebImage'
pod 'SVProgressHUD'

end

target 'ExampleAppTests' do

end

# ignore all warnings from all pods
inhibit_all_warnings!

